export const INTENT_RECOGNITION = {
    FETCH_DATASET: "FETCH_DATASET_TO_SELECT",
    FETCH_LANGUAGES: "FETCH_LANGUAGES_TO_SELECT",
    FETCH_COMMANDS: "FETCH_COMMANDS_TO_DISPLAY",
    SELECT_LANG: "CHANGE_SELECTED_LANG",
    SELECT_DATASET: "CHANGE_SELECTED_DATASET",
}


export const WAKE_WORD = {}